#!/bin/bash

curl https://overpass-api.de/api/interpreter?data=%5Btimeout%3A90000%5D%5Bout%3Ajson%5D%3Bnode%20%5Bnatural%3Dvolcano%5D%20%28-90%2C-90%2C90%2C90%29%3B%20out%20body%20qt%3B >> ~/osm-volcanoes.txt